unit Framework.Libraries.Validation.IsIntegerImpl.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  Framework.Libraries.Validation.Validate,
  Framework.Libraries.Validation.ValidateCustomAttributeImpl,
  System.Rtti,
  Framework.Libraries.Validation.IsIntegerImpl;

type
  // Test methods for class TIsInteger

  TestTIsInteger = class(TTestCase)
  strict private
    FIsInteger: TIsIntegerImpl;
  public
    const
    COLUMN_NAME: String = 'MyProp';
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure GetErrorMessage;
    procedure IsValidString;
    procedure IsValidInteger;
    procedure IsValidCurrency;
  end;

implementation

uses
  System.SysUtils,
  Framework.Libraries.Validation.ResourceStrings;



procedure TestTIsInteger.SetUp;
begin
  FIsInteger := TIsIntegerImpl.Create;
end;



procedure TestTIsInteger.TearDown;
begin
  FIsInteger.Free;
  FIsInteger := nil;
end;



procedure TestTIsInteger.GetErrorMessage;
begin
  CheckTrue(FIsInteger.GetErrorMessage = TResourceStringsValidator.RSValidation_IsInteger, 'Erro ao formatar mensagem');
end;



procedure TestTIsInteger.IsValidCurrency;
var
  AValue: TValue;
begin
  AValue := 0123.4;
  CheckFalse(FIsInteger.isValid(AValue), 'Não é um número inteiro: ' + AValue.ToString);
end;



procedure TestTIsInteger.IsValidInteger;
var
  AValue: TValue;
begin
  AValue := 01234;
  CheckTrue(FIsInteger.isValid(AValue), 'Erro ao validar o número: ' + AValue.ToString);
end;



procedure TestTIsInteger.IsValidString;
var
  AValue: TValue;
begin
  AValue := 'abcde';
  CheckFalse(FIsInteger.isValid(AValue), 'Não é um número inteiro: ' + AValue.ToString);
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTIsInteger.Suite);

end.
