unit Framework.Libraries.Validation.IsNaturalImpl.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  Framework.Libraries.Validation.Validate,
  Framework.Libraries.Validation.ValidateCustomAttributeImpl,
  Framework.Libraries.Validation.IsNaturalImpl,
  System.Rtti;

type
  // Test methods for class TIsNatural

  TestTIsNatural = class(TTestCase)
  strict private
    FIsNatural: TIsNaturalImpl;
  public
    const
    COLUMN_NAME: String = 'MyProp';
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure GetErrorMessage;
    procedure IsValidString;
    procedure IsValidStringNumber;
    procedure IsValidStringAphaNumeric;
    procedure IsValidCurrency;
    procedure IsValidInteger;
    procedure IsValidZero;
  end;

implementation

uses
  System.SysUtils,
  Framework.Libraries.Validation.ResourceStrings;



procedure TestTIsNatural.SetUp;
begin
  FIsNatural := TIsNaturalImpl.Create;
end;



procedure TestTIsNatural.TearDown;
begin
  FIsNatural.Free;
  FIsNatural := nil;
end;



procedure TestTIsNatural.GetErrorMessage;
begin
  CheckTrue(FIsNatural.GetErrorMessage = TResourceStringsValidator.RSValidation_IsNatural, 'Erro ao formatar mensagem');
end;



procedure TestTIsNatural.IsValidCurrency;
var
  AValue: TValue;
begin
  AValue := 0123.4;
  CheckFalse(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidInteger;
var
  AValue: TValue;
begin
  AValue := 1234;
  CheckTrue(FIsNatural.isValid(AValue), 'É um número natural maior que zero: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidString;
var
  AValue: TValue;
begin
  AValue := 'abcde';
  CheckFalse(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidStringAphaNumeric;
var
  AValue: TValue;
begin
  AValue := '123abc123';
  CheckFalse(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidStringNumber;
var
  AValue: TValue;
begin
  AValue := '123';
  CheckTrue(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidZero;
var
  AValue: TValue;
begin
  AValue := 0;
  CheckTrue(FIsNatural.isValid(AValue), 'É um número natural: ' + AValue.ToString);
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTIsNatural.Suite);

end.
