program concept_project_mvc;

uses
  //DBXDevartPostgreSQL,
  //DbxSqlite,
  Vcl.Forms,
  System.SysUtils,
  System.Classes,
  Spring.Container,
  Framework.Libraries.InterceptorLogger.MethodLoggerInterceptorImpl in '..\..\Framework\Libraries\InterceptorLogger\Framework.Libraries.InterceptorLogger.MethodLoggerInterceptorImpl.pas',
  Framework.Libraries.InterfacedObjectInjectedAttrImpl in '..\..\Framework\Libraries\Framework.Libraries.InterfacedObjectInjectedAttrImpl.pas',
  Framework.Libraries.InterfacedObjectLoggableImpl in '..\..\Framework\Libraries\Framework.Libraries.InterfacedObjectLoggableImpl.pas',
  Framework.Libraries.Logging.LoggingInitializeImpl in '..\..\Framework\Libraries\Logging\Framework.Libraries.Logging.LoggingInitializeImpl.pas',
  Framework.Libraries.Logging.Appenders.ConsoleAppenderImpl in '..\..\Framework\Libraries\Logging\Appenders\Framework.Libraries.Logging.Appenders.ConsoleAppenderImpl.pas',
  Framework.Libraries.Security.SecurityControllerImpl in '..\..\Framework\Libraries\Security\Framework.Libraries.Security.SecurityControllerImpl.pas',
  Framework.Libraries.Security.SecurityController in '..\..\Framework\Libraries\Security\Framework.Libraries.Security.SecurityController.pas',
  Framework.Libraries.Persistence.ORMPersistence in '..\..\Framework\Libraries\Persistence\Framework.Libraries.Persistence.ORMPersistence.pas',
  Framework.Libraries.Persistence.ORMPersistenceImpl in '..\..\Framework\Libraries\Persistence\Framework.Libraries.Persistence.ORMPersistenceImpl.pas',
  Framework.Libraries.Persistence.DBXAdapterImpl in '..\..\Framework\Libraries\Persistence\Framework.Libraries.Persistence.DBXAdapterImpl.pas',
  Framework.Libraries.DAO.GenericDAO in '..\..\Framework\Libraries\DAO\Framework.Libraries.DAO.GenericDAO.pas',
  Framework.Libraries.DAO.GenericDAOImpl in '..\..\Framework\Libraries\DAO\Framework.Libraries.DAO.GenericDAOImpl.pas',
  Framework.Libraries.Notification.NotificationMessage in '..\..\Framework\Libraries\Notification\Framework.Libraries.Notification.NotificationMessage.pas',
  Framework.Libraries.Notification.NotificationMessageImpl in '..\..\Framework\Libraries\Notification\Framework.Libraries.Notification.NotificationMessageImpl.pas',
  Framework.Libraries.Notification.NotificationService in '..\..\Framework\Libraries\Notification\Framework.Libraries.Notification.NotificationService.pas',
  Framework.Libraries.Notification.NotificationServiceImpl in '..\..\Framework\Libraries\Notification\Framework.Libraries.Notification.NotificationServiceImpl.pas',
  Framework.Libraries.Connection.ConnectionFactory in '..\..\Framework\Libraries\Connection\Framework.Libraries.Connection.ConnectionFactory.pas',
  Framework.Libraries.Connection.ConnectionFactoryImpl in '..\..\Framework\Libraries\Connection\Framework.Libraries.Connection.ConnectionFactoryImpl.pas',
  Framework.Libraries.UI.ViewFactoryImpl in '..\..\Framework\Libraries\UI\Framework.Libraries.UI.ViewFactoryImpl.pas',
  Framework.Libraries.UI.ViewRegistryImpl in '..\..\Framework\Libraries\UI\Framework.Libraries.UI.ViewRegistryImpl.pas',
  Framework.Libraries.Exceptions.ExceptionsClass in '..\..\Framework\Libraries\Exceptions\Framework.Libraries.Exceptions.ExceptionsClass.pas',
  Framework.Libraries.Validation.ModelMappingImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ModelMappingImpl.pas',
  Framework.Libraries.Validation.Validator in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.Validator.pas',
  Framework.Libraries.Validation.ValidatorImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ValidatorImpl.pas',
  Framework.Libraries.Validation.ExtendValidationImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ExtendValidationImpl.pas',
  Framework.Libraries.Validation.ResourceStrings in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ResourceStrings.pas',
  Framework.Libraries.Validation.Validate in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.Validate.pas',
  Framework.Libraries.Validation.ColumnTitleImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ColumnTitleImpl.pas',
  Framework.Libraries.Validation.ValidateCustomAttributeImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ValidateCustomAttributeImpl.pas',
  Framework.Libraries.Validation.MinLengthImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.MinLengthImpl.pas',
  Framework.Libraries.Validation.MaxLengthImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.MaxLengthImpl.pas',
  Framework.Libraries.Validation.MinValueImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.MinValueImpl.pas',
  Framework.Libraries.Validation.MaxValueImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.MaxValueImpl.pas',
  Framework.Libraries.Validation.ExactLengthImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ExactLengthImpl.pas',
  Framework.Libraries.Validation.RequiredImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.RequiredImpl.pas',
  Framework.Libraries.Validation.IsNaturalImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.IsNaturalImpl.pas',
  Framework.Libraries.Validation.IsNaturalNoZeroImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.IsNaturalNoZeroImpl.pas',
  Framework.Libraries.Validation.IsIntegerImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.IsIntegerImpl.pas',
  Framework.Libraries.Validation.RegexValidateImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.RegexValidateImpl.pas',
  Framework.Libraries.Validation.ValidEmailImpl in '..\..\Framework\Libraries\Validation\Framework.Libraries.Validation.ValidEmailImpl.pas',
  Framework.MVC.Controller.Initializable in '..\..\Framework\MVC\Controller\Framework.MVC.Controller.Initializable.pas',
  Framework.MVC.Controller.BaseController in '..\..\Framework\MVC\controller\Framework.MVC.Controller.BaseController.pas',
  Framework.MVC.Controller.BaseControllerImpl in '..\..\Framework\mvc\controller\Framework.MVC.Controller.BaseControllerImpl.pas',
  Framework.MVC.Controller.CRUDController in '..\..\Framework\MVC\Controller\Framework.MVC.Controller.CRUDController.pas',
  Framework.MVC.Controller.CRUDControllerImpl in '..\..\Framework\MVC\Controller\Framework.MVC.Controller.CRUDControllerImpl.pas',
  Framework.MVC.Controller.ORMCRUDController in '..\..\Framework\MVC\Controller\Framework.MVC.Controller.ORMCRUDController.pas',
  Framework.MVC.Controller.ORMCRUDControllerImpl in '..\..\Framework\MVC\Controller\Framework.MVC.Controller.ORMCRUDControllerImpl.pas',
  Framework.MVC.Model.BaseModel in '..\..\Framework\MVC\Model\Framework.MVC.Model.BaseModel.pas',
  Framework.MVC.Model.BaseModelImpl in '..\..\Framework\MVC\Model\Framework.MVC.Model.BaseModelImpl.pas',
  Framework.MVC.View.UI.BaseForm in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.BaseForm.pas' {BaseFormView},
  Framework.MVC.View.UI.Cadastro in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Cadastro.pas',
  Framework.MVC.View.UI.Configuracao in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Configuracao.pas',
  Framework.MVC.View.UI.Consulta in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Consulta.pas' {FormConsulta},
  Framework.MVC.View.UI.FormularioInterno in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.FormularioInterno.pas' {FormFormularioInterno},
  Framework.MVC.View.UI.Processo.CRUD in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Processo.CRUD.pas' {FormProcessoCRUD},
  Framework.MVC.View.UI.Processo in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Processo.pas' {FormProcesso},
  Framework.MVC.View.UI.Relatorio in '..\..\Framework\MVC\View\UI\Framework.MVC.View.UI.Relatorio.pas' {FormRelatorio},
  UFrmPrincipal in '..\pas\UFrmPrincipal.pas' {FrmPrincipal},
  MVCDemo.Registers.RegisterViewsImpl in '..\pas\Registers\MVCDemo.Registers.RegisterViewsImpl.pas',
  MVCDemo.Registers.RegisterTypesImpl in '..\pas\Registers\MVCDemo.Registers.RegisterTypesImpl.pas',
  MVCDemo.Controllers.CRM.PaisController in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.PaisController.pas',
  MVCDemo.Controllers.CRM.PaisControllerImpl in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.PaisControllerImpl.pas',
  MVCDemo.Controllers.CRM.EstadoController in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.EstadoController.pas',
  MVCDemo.Controllers.CRM.EstadoControllerImpl in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.EstadoControllerImpl.pas',
  MVCDemo.Controllers.CRM.MunicipioController in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.MunicipioController.pas',
  MVCDemo.Controllers.CRM.MunicipioControllerImpl in '..\pas\Controllers\CRM\MVCDemo.Controllers.CRM.MunicipioControllerImpl.pas',
  MVCDemo.Controllers.Comercial.MarcaController in '..\pas\Controllers\Comercial\MVCDemo.Controllers.Comercial.MarcaController.pas',
  MVCDemo.Controllers.Comercial.MarcaControllerImpl in '..\pas\Controllers\Comercial\MVCDemo.Controllers.Comercial.MarcaControllerImpl.pas',
  MVCDemo.Models.Base.UsuarioModel in '..\pas\Models\Base\MVCDemo.Models.Base.UsuarioModel.pas',
  MVCDemo.Models.Base.UsuarioModelPKImpl in '..\pas\Models\Base\MVCDemo.Models.Base.UsuarioModelPKImpl.pas',
  MVCDemo.Models.Base.UsuarioModelImpl in '..\pas\Models\Base\MVCDemo.Models.Base.UsuarioModelImpl.pas',
  MVCDemo.Models.CRM.PaisModel in '..\pas\Models\CRM\MVCDemo.Models.CRM.PaisModel.pas',
  MVCDemo.Models.CRM.PaisModelPKImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.PaisModelPKImpl.pas',
  MVCDemo.Models.CRM.PaisModelImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.PaisModelImpl.pas',
  MVCDemo.Models.CRM.EstadoModel in '..\pas\Models\CRM\MVCDemo.Models.CRM.EstadoModel.pas',
  MVCDemo.Models.CRM.EstadoModelPKImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.EstadoModelPKImpl.pas',
  MVCDemo.Models.CRM.EstadoModelImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.EstadoModelImpl.pas',
  MVCDemo.Models.CRM.MunicipioModel in '..\pas\Models\CRM\MVCDemo.Models.CRM.MunicipioModel.pas',
  MVCDemo.Models.CRM.MunicipioModelPKImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.MunicipioModelPKImpl.pas',
  MVCDemo.Models.CRM.MunicipioModelImpl in '..\pas\Models\CRM\MVCDemo.Models.CRM.MunicipioModelImpl.pas',
  MVCDemo.Models.Comercial.MarcaModel in '..\pas\Models\Comercial\MVCDemo.Models.Comercial.MarcaModel.pas',
  MVCDemo.Models.Comercial.MarcaModelPKImpl in '..\pas\Models\Comercial\MVCDemo.Models.Comercial.MarcaModelPKImpl.pas',
  MVCDemo.Models.Comercial.MarcaModelImpl in '..\pas\Models\Comercial\MVCDemo.Models.Comercial.MarcaModelImpl.pas',
  MVCDemo.DAOs.CRM.PaisDAO in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.PaisDAO.pas',
  MVCDemo.DAOs.CRM.PaisDAOImpl in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.PaisDAOImpl.pas',
  MVCDemo.DAOs.CRM.EstadoDAO in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.EstadoDAO.pas',
  MVCDemo.DAOs.CRM.EstadoDAOImpl in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.EstadoDAOImpl.pas',
  MVCDemo.DAOs.CRM.MunicipioDAO in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.MunicipioDAO.pas',
  MVCDemo.DAOs.CRM.MunicipioDAOImpl in '..\pas\DAOs\CRM\MVCDemo.DAOs.CRM.MunicipioDAOImpl.pas',
  MVCDemo.DAOs.Comercial.MarcaDAO in '..\pas\DAOs\Comercial\MVCDemo.DAOs.Comercial.MarcaDAO.pas',
  MVCDemo.DAOs.Comercial.MarcaDAOImpl in '..\pas\DAOs\Comercial\MVCDemo.DAOs.Comercial.MarcaDAOImpl.pas',
  MVCDemo.Views.CRM.PaisView in '..\pas\Views\CRM\MVCDemo.Views.CRM.PaisView.pas' {FrmPaisView},
  MVCDemo.Views.CRM.EstadoView in '..\pas\Views\CRM\MVCDemo.Views.CRM.EstadoView.pas' {FrmEstadoView},
  MVCDemo.Views.CRM.MunicipioView in '..\pas\Views\CRM\MVCDemo.Views.CRM.MunicipioView.pas' {FrmMunicipioView},
  MVCDemo.Views.Comercial.MarcaView in '..\pas\Views\Comercial\MVCDemo.Views.Comercial.MarcaView.pas' {FrmMarcaView};

{R *.res}




begin

  RegisterTypes();

  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Run;

end.

