unit MVCDemo.Models.Base.UsuarioModelPKImpl;

interface

uses
  Spring.Persistence.Mapping.Attributes,
  Spring.Container.Common,
  Framework.MVC.Model.BaseModelImpl,
  MVCDemo.Models.Base.UsuarioModel,
  Framework.Libraries.Validation.ValidatorImpl;

type

  [Entity]
  [Table('tb_usuario')]
  [Sequence('gen_usuario', 1, 1)]
  TUsuarioModelPKImpl = class(TMVCBaseModelImpl, IUsuarioModel)
  private
    FCodigo: Integer;
  private
    procedure SetCodigo(const Value: Integer);
  public
    [Column('id_usuario', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'CÓDIGO DO USUÁRIO')]
    [ColumnTitle('Código')]
    [IsNaturalNoZero]
    // [AutoGenerated]
    property Codigo: Integer read FCodigo write SetCodigo;
  end;

implementation

uses
  DSharp.Bindings;

{ TUsuarioModelPKImpl }



procedure TUsuarioModelPKImpl.SetCodigo(const Value: Integer);
begin
  if (FCodigo <> Value) then
  begin
    FCodigo := Value;
    NotifyPropertyChanged(Self, 'Codigo');
  end;
end;

end.
