unit MVCDemo.Models.Comercial.MarcaModelPKImpl;

interface

uses
  Spring.Persistence.Mapping.Attributes,
  Spring.Container.Common,
  Framework.MVC.Model.BaseModelImpl,
  MVCDemo.Models.Comercial.MarcaModel,
  Framework.Libraries.Validation.ValidatorImpl;

type

  [Entity]
  [Table('tb_marca')]
  [Sequence('gen_marca', 1, 1)]
  TMarcaModelPKImpl = class(TMVCBaseModelImpl, IMarcaModel)
  private
    FCodigo: Integer;
  private
    procedure SetCodigo(const Value: Integer);
  public
    [Column('id_marca', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'CÓDIGO DA MARCA')]
    [ColumnTitle('Código')]
    [IsNaturalNoZero]
    // [AutoGenerated]
    property Codigo: Integer read FCodigo write SetCodigo;
  end;

implementation

uses
  DSharp.Bindings;

{ TMarcaModelPKImpl }



procedure TMarcaModelPKImpl.SetCodigo(const Value: Integer);
begin
  if (FCodigo <> Value) then
  begin
    FCodigo := Value;
    NotifyPropertyChanged(Self, 'Codigo');
  end;
end;

end.
