unit MVCDemo.Models.CRM.MunicipioModelPKImpl;

interface

uses
  Spring.Persistence.Mapping.Attributes,
  Framework.MVC.Model.BaseModelImpl,
  MVCDemo.Models.CRM.MunicipioModel,
  Framework.Libraries.Validation.ValidatorImpl;

type

  [Entity]
  [Table('tb_municipio')]
  [Sequence('gen_municipio', 1, 1)]
  TMunicipioModelPKImpl = class(TMVCBaseModelImpl, IMunicipioModel)
  private
    FCodigo: Integer;
    procedure SetCodigo(const Value: Integer);
  public
    [Column('id_municipio', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'CÓDIGO DO MUNICÍPIO')]
    [ColumnTitle('Código')]
    [IsNatural]
    // [AutoGenerated]
    property Codigo: Integer read FCodigo write SetCodigo;
  end;

implementation

uses
  DSharp.Bindings;

{ TMunicipioModelPKImpl }



procedure TMunicipioModelPKImpl.SetCodigo(const Value: Integer);
begin
  if (FCodigo <> Value) then
  begin
    FCodigo := Value;
    NotifyPropertyChanged(Self, 'Codigo');
  end;
end;

end.
