unit MVCDemo.Models.CRM.SPEDECFPaisesModelPKImpl;

interface

uses
  Framework.MVC.Model.BaseModelImpl,
  MVCDemo.Models.CRM.SpedECFPaisesModel,
  Framework.Libraries.Validation.ValidatorImpl,
  Spring.Persistence.Mapping.Attributes;

type

  [Entity]
  [Table('TB_SPEDECFPAISES')]
  TSPEDECFPaisesModelPKImpl = class(TMVCBaseModelImpl, ISPEDECFPaisesModel)
  private
    FCodigo: Integer;
  private
    procedure SetCodigo(const Value: Integer);
  public
    [Column('CD_CODIGO', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'CÓDIGO DO PAÍS SPED ECF')]
    // [AutoGenerated]
    [ColumnTitle('Código')]
    [IsNaturalNoZero]
    property Codigo: Integer read FCodigo write SetCodigo;
  end;

implementation

uses
  DSharp.Bindings;

{ TSPEDECFPaisesModelPKImpl }



procedure TSPEDECFPaisesModelPKImpl.SetCodigo(const Value: Integer);
begin
  if (FCodigo <> Value) then
  begin
    FCodigo := Value;
    NotifyPropertyChanged(Self, 'Codigo');
  end;
end;

end.
